# Python Data Science Handbook 

These are tests and examples from the Python Data Science Handbook by Jake VanderPlas


In [8]:
import numpy as np #this is convention with the data science community

Numpy allows for arrays to be created using the <code>array</code> function. Arrays must contain data all of the same type. This can be specified by passing a <code>dtype=''</code> argument into the <code>array</code> function.

In [14]:
print(np.array([1,2,3,4,5]))
print(np.array([1,2,3,4,5], dtype='float32'))

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


### Multi-dimensional support
Arrays can also be multidimensional

In [10]:
print(np.array([range(i,i+3)for i in [2,4,6]]))

[[2 3 4]
 [4 5 6]
 [6 7 8]]


### Cell creation/initialization
Arrays can also be created using <code>np.zeros()</code>, <code>np.ones()</code> or <code>np.full()</code>

In [15]:
print(np.zeros(10))
print(np.ones([3,5]))
print(np.full([2,2],3.14))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14]
 [3.14 3.14]]


Arrays with arranged values can be created with <code>np.arange()</code> or <code>np.linspace()</code>

In [17]:
print(np.arange(0,20,2))
print(np.linspace(0,1,5))

[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


Random arrays can be created with <code>np.random.random()</code>, <code>np.random.normal()</code> and <code>np.random.ranint()</code>

In [22]:
print(np.random.random((3,3)))
print(np.random.normal(0,1,(3,3)))
print(np.random.randint(0,10,(3,3)))

[[0.20744662 0.87237186 0.51670087]
 [0.89345089 0.74281397 0.20758901]
 [0.10400782 0.76900137 0.10438042]]
[[ 0.03364685  0.71238705 -1.49553488]
 [-1.15396002 -1.21548978 -1.21460933]
 [ 0.28548836 -0.30858931  0.49464989]]
[[2 5 0]
 [0 4 2]
 [8 8 7]]


### Indexing
Indexing in numpy arrays is the same as in python lists or touples. Slicing can be subsituted in any place an index could be used.

In [28]:
x1 = np.arange(10)
print('x1 = ',x1)
print(x1[0])
print(x1[:5])
print(x1[::-1])

x1 =  [0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]
[9 8 7 6 5 4 3 2 1 0]


indexing and slicing works on multi-dimensional arrays in the same way

In [36]:
x2 = np.random.randint(0,10,(3,4))
print(x2)
print(x2[0,0])
print(x2[-1,:])
print(x2[:,1])

[[3 9 1 9]
 [9 9 9 4]
 [5 5 6 4]]
3
[5 5 6 4]
[9 9 5]


### Arithmetic
All default computational operations can be performed on arrays
numpy arithmetic function are computed using vectorization which is much faster than the standard python list arithmetic which uses iteration


In [9]:
x = np.arange(4)
print('x+5=',x+5)
print('x-5=',x-5)
print('x*2=',x*2)
print('x/2=',x/2)
print('x**2=',x**2)

x+5= [5 6 7 8]
x-5= [-5 -4 -3 -2]
x*2= [0 2 4 6]
x/2= [0.  0.5 1.  1.5]
x**2= [0 1 4 9]
